# Generated by Django 2.2.3 on 2019-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarklo', '0002_oglas_kategorija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='slika',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
