# Generated by Django 2.2.3 on 2019-08-28 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sarklo', '0004_auto_20190828_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
