# Generated by Django 2.2.3 on 2019-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarklo', '0005_oglas_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='kategorija',
            field=models.CharField(choices=[('ODM', 'Odeca Muska'), ('ODZ', 'Odeca Zenska'), ('OBM', 'Obuca Muska'), ('OBZ', 'Obuca Zenska'), ('KGS', 'Knjige Skolske'), ('KGO', 'Knjige Ostale'), ('IG', 'Igracke'), ('TE', 'Tehnika'), ('RK', 'Rukotvorine')], default='KGS', max_length=2),
        ),
    ]
