# Generated by Django 2.2.3 on 2019-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarklo', '0006_auto_20190829_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='kategorija',
            field=models.CharField(choices=[('OM', 'Odeca Muska'), ('OZ', 'Odeca Zenska'), ('BM', 'Obuca Muska'), ('BZ', 'Obuca Zenska'), ('KS', 'Knjige Skolske'), ('KO', 'Knjige Ostale'), ('IG', 'Igracke'), ('TE', 'Tehnika'), ('RK', 'Rukotvorine')], default='KS', max_length=2),
        ),
    ]
