# Generated by Django 2.2.7 on 2019-11-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarklo', '0008_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='author',
            new_name='oglas',
        ),
    ]
